#!/bin/zsh

# NOTE: ENV
export DOTFILES="$HOME/.local/share/chezmoi"
export ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
export SCRIPTS="$DOTFILES/scripts"
export PATH="$SCRIPTS:$HOME/.local/bin:$PATH"

export EDITOR="nvim"
export VISUAL="nvim"
export GITHUB_USERNAME="druwan"
export LANG=en_US.UTF-8

# NOTE: Activate tools through mise
if command -v mise > /dev/null 2>&1; then
  eval "$(mise activate zsh)"
fi

mkdir -p "$ZSH_CACHE_DIR/completions"
fpath=("$ZSH_CACHE_DIR/completions" $fpath)

# NOTE: Detect OS
OS="$(uname)"
# Detect if WSL2
if [[ "$OS" == "Linux" ]]; then
  OS_RELEASE=$(cat /proc/sys/kernel/osrelease 2>/dev/null)
  OS=$([[ "$OS_RELEASE" == *"WSL2"* ]] && echo "WSL2" || echo "Linux")
fi

case "$OS" in
  "Darwin")
    export NOTES="$HOME/Library/CloudStorage/OneDrive-Personal/ObsidianVault"
    if [[ -z "$SSH_AUTH_SOCK" || ! -S "$SSH_AUTH_SOCK" ]]; then
      local MAC_SSH=$(launchctl getenv SSH_AUTH_SOCK)
      [[ -S "$MAC_SSH" ]] && export SSH_AUTH_SOCK="$MAC_SSH"
    fi
    # NOTE: BREW
    if type brew &>/dev/null; then
      FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
      alias update='brew update && brew upgrade && brew upgrade --cask --greedy && ani-cli -U'
    fi
    ;;
  "Linux"|"WSL2")
    [[ "$OS" == "WSL2" ]] && export NOTES="/mnt/c/Users/druwa/OneDrive/ObsidianVault"
    [[ -z "$SSH_AUTH_SOCK" ]] && export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR:-/tmp}/ssh-agent.socket"
    ;;
esac

# NOTE: History
HISTFILE="$HOME/.zsh_history"
HIST_STAMPS="dd/mm/yyyy"
HISTSIZE=100000
SAVEHIST=100000
setopt HIST_IGNORE_SPACE HIST_IGNORE_DUPS SHARE_HISTORY

# NOTE: Aliases
[[ -n "$NOTES" ]] && alias notes="cd \"$NOTES\""
alias history='history 1'

if command -v nvim >/dev/null; then
  alias v="nvim" vi="nvim" vim="nvim"
else
  alias v="vim"
fi

alias ls="ls --color=auto"
alias ll="ls -lh"
alias la="ls -lah"
if command -v lsd > /dev/null; then
  alias ls="lsd"
  alias la="ls -alh --group-dirs first"
fi
  alias ll="ls -lh --group-dirs first"

command -v tree > /dev/null && alias tree="tree -v --dirsfirst"
command -v kubectl >/dev/null && { source <(kubectl completion zsh); alias k="kubectl"; compdef k=kubectl; }


# NOTE: Tools
if command -v mise > /dev/null 2>&1; then
  eval "$(mise activate zsh)"
fi

if command -v fzf > /dev/null 2>&1; then
  source <(fzf --zsh)
fi


load_completion() {
  local name=$1
  local cmd=$2
  if [[ ! -f "$ZSH_CACHE_DIR/completions/_$name" ]]; then
    # Only run if tool exist in PATH
    if command -v "$name" >/dev/null; then
      echo "Generating completion for $name..."
      eval "$cmd" > "$ZSH_CACHE_DIR/completions/_$name"
    fi
  fi
}

for tool in kubectl helm uv chezmoi docker devpod flux; do
  case $tool in
    uv) load_completion "uv" "uv generate-shell-completion zsh" ;;
    *) load_completion "$tool" "$tool completion zsh" ;;
  esac
done

autoload -Uz compinit
compinit -u

# NOTE: Private ENV
[[ -f "$HOME/.privaterc.sh" ]] && source "$HOME/.privaterc.sh"

ZSH_HIGHLIGHT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh/zsh-syntax-highlighting"
[[ -f "$ZSH_HIGHLIGHT_DIR/zsh-syntax-highlighting.zsh" ]] && source "$ZSH_HIGHLIGHT_DIR/zsh-syntax-highlighting.zsh"

# NOTE: Prompt
if command -v starship >/dev/null 2>&1; then
  eval "$(starship init zsh)"
fi



