[tools]
bat = "latest"
chezmoi = "latest"
fd = "latest"
flux2 = "latest"
fzf = "latest"
kubectl = "latest"
lsd = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
