[window]
decorations = "full"
opacity = 0.6
blur = true
padding = { x = 5, y = 0 }


[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Bold" }

[general]
# themes from https://github.com/alacritty/alacritty-theme
# import = ["~/.config/alacritty/catppuccin-mocha.toml"]
import = ["~/.config/alacritty/tokyonight-night.toml"]
